name: Trigger JitPack Build

on:
  push:
    tags: 
      - '*'

env:
  ORG: slaterin

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger Build in JitPack
      run: echo "curl https://jitpack.io/com/github/${ORG}/${GITHUB_REPOSITORY}/${GITHUB_REF#refs/tags/}"
